//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLTW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int ID { get; set; }
        public string TypeCode { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public System.DateTime EntryTime { get; set; }
        public string Content { get; set; }
        public Nullable<long> CountView { get; set; }
        public string ImageThumbnail { get; set; }
        public bool IsDuyet { get; set; }
    
        public virtual TheLoai TheLoai { get; set; }
    }
}
